### ISSUE TITLE
Same exported MAST in different module resolution

### ISSUE THREAD

**Issue by frisitano** [0xMiden/miden-vm#1022]
When we have two modules with an exported procedure that compiles to the same MAST the compiler is unable to resolve one of the procedures due to the way it is cached in the `ProcedureCache`.  When an attempt it made to insert a procedure into the `ProcedureCache` the cache checks if the MAST already exists in the cache and then assesses consistency of the procedure metadata (num locals).  If a match is found for a MAST then the second procedure will not modify the procedure cache, more specifically the `proc_id` will not be added to the `proc_id_map`.  See below:

https://github.com/0xPolygonMiden/miden-vm/blob/75887673612c6d5c17b4a24d588dc05b7defe7f1/assembly/src/assembler/procedure_cache.rs#L67-L84

This means that when we try and execute both of these procedures by Id reference, one of them will not be found as it is not in the `proc_id_map`.  See the code example and associated failing test on the following PR given as an example:
https://github.com/0xPolygonMiden/miden-vm/pull/1021

There should be an easy fix to by ensuring that we update the `proc_id_map` even if we have a mast root collision:

```rust
        match self.procedures.entry(proc.mast_root()) {
            Entry::Occupied(cached_proc_entry) => {
                let cached_proc = cached_proc_entry.get();
                if proc.num_locals() != cached_proc.num_locals() {
                    Err(AssemblyError::conflicting_num_locals(proc.name()))
                } else {
                    self.proc_id_map.entry(*proc.id()).or_insert(proc.mast_root());  <-- this addition.
                    Ok(())
                }
            }
            Entry::Vacant(entry) => {
                self.proc_id_map.entry(*proc.id()).or_insert(proc.mast_root());
                entry.insert(proc.into_inner());
                Ok(())
            }
        }
    }
```

**Comment by bobbinth** [comment]
Great catch! I actually intended for it to work exactly like this, but somehow forgot to add this line.
