### ISSUE TITLE
Design the pseudo-random field elements generator using RPO

### ISSUE THREAD

**Issue by Al-Kindi-0** [0xMiden/miden-vm#751]
During recursive verification, we need to use RPO as a random oracle in order to render the interactive protocol non-interactive. In Winterfell, this is achieved using the `Random_Coin<BaseField, RPO>` struct in order to get a random oracle, call it `public_coin`. The `Random_Coin` struct has two fields; `Seed` and `Counter`:

1. Seed is used for reseeding via `public_coin.reseed(digest)` (or `public_coin.reseed_with_int(integer)`) which basically sets `public_coin`'s seed to a new value computed as `RPO::merge(public_coin.seed, digest)` (or `RPO::merge_with_int(public_coin.seed, integer)`). After reseeding, the internal counter is set to zero.
2. Counter is incremented when `public_coin.next()` is used to draw the next random word as `RPO::merge_with_int(public_coin.seed, public_coin.counter)`.

This issue aims at investigating the changes, if any, needed in Winterfell in order to render the `Random_Coin` struct friendlier for recursive verification. More precisely, the following questions need to be investigated:

1. The public inputs are used to initialize the seed for `public_coin`. This is done by writing the public inputs into a `Vec<u8>` and then hashing the latter in order to get an initial seed. Do the padding rules for RPO allow us to avoid passing by `Vec<u8>` and hash instead field elements directly? It seems to be the case but we should double check.
2. Is the current implementation of `reseed_with_int` optimal with regards to RPO?
3. For drawing many field elements it seems rather wasteful, in the context of RPO, to have to run one permutation per 1 random field element drawn. Should we change this?

**Comment by bobbinth** [comment]
Yes, I think all 3 of these could be improved in Winterfell and it would make the assembly code both more performant and simpler.

**Comment by jan-ferdinand** [comment]
In Triton, we have one global (resetable) Sponge state. When recursively verifying, we use it for the Fiat-Shamir transform[^1]. Seeding is implicitly done through absorption. Multiple pseudo-random field elements can easily be generated by squeezing multiple times, without the need to keep track of any counters.

[^1]: among other things; After all challenges have been generated, we also use it for hashing of inputs with variable length.

**Comment by Al-Kindi-0** [comment]
Yes, I believe this is the way it is (was?) done in Halo2 and Kimchi as well.
The reason for the current way of doing things is related to the fact that Winterfell doesn't assume that the hash function is a sponge. I am also not sure how many changes are needed to support this in Winterfell.

**Comment by jan-ferdinand** [comment]
Apologies for rambling about an approach you are familiar with; I don't know the constraints imposed by Winterfell and that those might disqualify said approach. :relieved:

**Comment by bobbinth** [comment]
I actually think it might be a good idea to refactor `RandomCoin` struct in Winterfell to be a trait which could be provided for specific instances of prover/verifier. This would help with this issue but also probably with #753.

**Comment by Al-Kindi-0** [comment]
Yes, makes sense! This way we can make use of the sponge structure of RPO as @jan-ferdinand suggested above.

**Comment by Al-Kindi-0** [comment]
Created an issue here https://github.com/facebook/winterfell/issues/162

**Comment by Al-Kindi-0** [comment]
Closed by #891
